### ISSUE TITLE
Renamed folder never fetches

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/sync#91]
There is a sync profile on a staging server:
squalider piccalilli mutate decomposability
waterily nonaligned watershed homeward
aidman tat nobleman filling
chromaticism copolymerizing prythee gonococci
The problem folder `objectId` is `26,251,177,91,209,203,139,31,24,56,137,33,64,29,161,167`. The folder was first created with a name `1` and was renamed after to `123456`. On a fetch on `GET_EXISTING_OBJECTS` I see those two records one is with a create action and another one is with an update action. I put `null` as a correspondent object to them as I don't have them locally and call `RESOLVE`, but I never see any of them on `RESOLVED`. Instead of that I see that in my console `"Ignoring 1 of object 26,251,177,91,209,203,139,31,24,56,137,33,64,29,161,167."`

**Comment by ayumi** [comment]
I found the problem, looks like it's in sync client/recordUtil mergeRecords() when we try to collapse same objectId records within a batch of recordsAndExistingObjects – the props of the newer records take precedence, which makes sense for objectData but not for type (Create + Update should merge to a single Create, not an Update).

This has been okay in browser-laptop because the resultant Update re-resolves to a Create.
However, this profile (from Android?) has folder title property as `"title"`, but the sync lib checks for `customTitle` as that's the browser-laptop convention. Thus the Update is discarded as invalid.

**Comment by ayumi** [comment]
@SergeyZhukovsky The latest sync bundle 1.3.0 should have the fix now. let me know how it goes :cherries:
